### ISSUE TITLE
Channels with '&' prefix aren't accessible by Quassel

### ISSUE THREAD

**Issue by rodneyrod** [baines/morpheus#1]
Steps to reproduce:
1. Join 'Linux' room on matrix.org (I'm using that as an example since it shows as &group_CbWGSqXrUpGnRUglfe:matrix.org in Quassel)
2. Connect to morpheus through Quassel
3. The room '&group_CbWGSqXrUpGnRUglfe:matrix.org' shows up as inactive and disconnected. Messages will be received as they come in but all replies are dropped since Quassel thinks the room is disconnected.

A workaround to this could be to add a '#' prefix to such rooms, but as you can't rename rooms clientside on Quassel I can't test this myself.

**Comment by baines** [comment]
Currently the support for matrix rooms without a canonical alias is unfortunately pretty half-baked.

I had the idea at some point to treat rooms with >2 members and no canonical alias as "&group_" + matrix_id, like you're seeing, but I wasn't particularly happy with that solution and it never got much testing, so the problem might be the handling of these rooms in general instead of the first char not being '#'.

I'd like to add in checking for non-canonical aliases on the homeserver that morpheus is connected to, or converting the room.name to something IRC compatible and unique eventually, but for the time being I'll do some testing of the "&group_" conversion code and see if there's something obviously broken there.

**Comment by rodneyrod** [comment]
I'm not too well versed in the Matrix API, but there should be a way to get the human readable name from there, then rename the room to that on clientside, and if the names match any existing room, just append a number on the end and possibly expose a way to rename the room on the IRC side through morpheus.

**Comment by baines** [comment]
I've improved the room naming code in 880a6ba, it should use the best "normal" alias from the connected homeserver now when no canonical alias exists.

I connected to the Linux room on matrix.org and it now creates a "#linux" irc room which makes more sense. Sending/receiving messages to it seemed to work fine from the short amount of testing I did (with weechat).

**Comment by rodneyrod** [comment]
Just did a git pull and restarted the daemon, it's still calling the room &group_CbWGSqXrUpGnRUglfe:matrix.org.

Would I have to clear my config or something? Also, if possible try to test it out with Quassel to see if you can repeat the issue on your end.

**Comment by baines** [comment]
Did you rerun make? I think I completely removed the &group_ naming thing, so it might be something is being cached by Quassel. I'll download it and do some testing.

Edit: It seemed to work ok on my machine™
![quassel2](https://user-images.githubusercontent.com/1444224/32694072-c2c34e42-c72e-11e7-9dfc-3edf645d67e2.png)

**Comment by rodneyrod** [comment]
I did not remake, I have and it works now. Thanks for fixing this.
